# Generated by Django for Beacon auth migration consistency.

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_case_insensitive_account_uniqueness"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
