<template>
  <AuthPage
    mode="login"
    title="auth.loginTitle"
    description="auth.loginDescription"
    endpoint="/api/auth/login/"
    input-id="login-email"
    submit-label="auth.loginSubmit"
    success-message="auth.loginSuccess"
    error-message="auth.loginError"
    alternate-to="/signup"
    alternate-label="auth.signupLink"
  />
</template>
