<template>
  <AuthScreen
    mode="signup"
    title="auth.signupTitle"
    description="auth.signupDescription"
    endpoint="/api/auth/signup/"
    input-id="signup-email"
    submit-label="auth.signupSubmit"
    success-message="auth.signupSuccess"
    error-message="auth.signupError"
    alternate-to="/login"
    alternate-label="auth.loginLink"
    clear-on-success
  />
</template>
