# Generated by Django 5.2.15 on 2026-07-16 11:00

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("STANDALONE_WORK", "Standalone Work"),
                            ("RECOGNIZED_SERIES", "Recognized Series"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.TextField()),
                ("title_normalized", models.TextField()),
                ("author_names", models.TextField()),
                ("author_names_normalized", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                ("external_reference_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="INACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_canonical", models.BooleanField(default=False)),
                (
                    "duplicate_risk_status",
                    models.CharField(
                        choices=[
                            ("LOW_RISK", "Low Risk"),
                            ("HIGH_RISK", "High Risk"),
                            ("NEEDS_REVIEW", "Needs Review"),
                        ],
                        default="LOW_RISK",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not Required"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_REQUIRED",
                        max_length=20,
                    ),
                ),
                ("recommendation_cycle_number", models.PositiveIntegerField(default=0)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("last_support_at", models.DateTimeField(blank=True, null=True)),
                ("support_count", models.PositiveIntegerField(default=0)),
                (
                    "on_chain_program_account",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "on_chain_recommendation_seed",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_recommender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="recommendations.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CuratorFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DuplicateReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED_DUPLICATE", "Confirmed Duplicate"),
                            ("NOT_DUPLICATE", "Not Duplicate"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reports",
                        to="recommendations.bookrecommendation",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicate_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspected_duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspected_duplicates",
                        to="recommendations.bookrecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommenderParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked_amount_lamports", models.BigIntegerField(default=0)),
                ("initial_lock_at", models.DateTimeField()),
                ("last_stake_change_at", models.DateTimeField(blank=True, null=True)),
                ("reclaimed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("reactivation_number", models.PositiveIntegerField(default=0)),
                (
                    "on_chain_stake_account",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "on_chain_lock_transaction",
                    models.CharField(blank=True, max_length=88, null=True),
                ),
                (
                    "on_chain_reclaim_transaction",
                    models.CharField(blank=True, max_length=88, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommender_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommender_participants",
                        to="recommendations.bookrecommendation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReputationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DISCOVERY", "Discovery"),
                            ("REACTIVATION", "Reactivation"),
                            ("SUPPORT_RECEIVED", "Support Received"),
                            ("BADGE_EARNED", "Badge Earned"),
                        ],
                        max_length=50,
                    ),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reputation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reputation_events",
                        to="recommendations.bookrecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supporter_number", models.PositiveIntegerField()),
                ("amount_lamports", models.BigIntegerField(default=10000000)),
                ("recommendation_cycle_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "on_chain_support_transaction",
                    models.CharField(blank=True, max_length=88, null=True),
                ),
                (
                    "on_chain_support_account",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supports",
                        to="recommendations.bookrecommendation",
                    ),
                ),
                (
                    "supporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supports_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["recommendation", "supporter_number"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks_by_users",
                        to="recommendations.bookrecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "-created_at"],
                        name="bookmark_account_created_idx",
                    ),
                    models.Index(
                        fields=["recommendation", "-created_at"],
                        name="bookmark_rec_created_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("account"),
                        models.F("recommendation"),
                        name="bookmark_one_per_account_per_recommendation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("DIAMOND", "Diamond"),
                        ],
                        max_length=20,
                    ),
                ),
                ("earned_at", models.DateTimeField()),
                (
                    "on_chain_mint_transaction",
                    models.CharField(blank=True, max_length=88, null=True),
                ),
                (
                    "on_chain_mint_account",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="recommendations.bookrecommendation",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "-earned_at"],
                        name="badge_account_earned_idx",
                    ),
                    models.Index(
                        fields=["recommendation", "tier"], name="badge_rec_tier_idx"
                    ),
                    models.Index(
                        fields=["recommendation", "account"],
                        name="badge_rec_account_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("account"),
                        models.F("recommendation"),
                        models.F("tier"),
                        name="badge_one_per_tier_per_account_per_recommendation",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["status", "-created_at"], name="bookrec_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["-support_count"], name="bookrec_support_count_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["creator", "-created_at"], name="bookrec_creator_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["category", "status", "-support_count"],
                name="bookrec_cat_status_support_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["last_support_at"], name="bookrec_last_support_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookrecommendation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title_normalized"),
                django.db.models.functions.text.Lower("author_names_normalized"),
                models.F("page_type"),
                condition=models.Q(("is_canonical", True)),
                name="bookrecommendation_canonical_work_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="curatorfollow",
            index=models.Index(
                fields=["followee", "-created_at"],
                name="curfollow_followee_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="curatorfollow",
            index=models.Index(
                fields=["follower", "-created_at"],
                name="curfollow_follower_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatorfollow",
            constraint=models.UniqueConstraint(
                models.F("follower"),
                models.F("followee"),
                name="curatorfollow_one_per_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatorfollow",
            constraint=models.CheckConstraint(
                condition=models.Q(("follower", models.F("followee")), _negated=True),
                name="curatorfollow_no_self_follow",
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatereport",
            index=models.Index(
                fields=["recommendation", "status"], name="dupreport_rec_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatereport",
            index=models.Index(
                fields=["status", "-created_at"], name="dupreport_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatereport",
            constraint=models.UniqueConstraint(
                models.F("reporter"),
                models.F("recommendation"),
                name="duplicatereport_one_per_reporter_per_recommendation",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatereport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recommendation", models.F("suspected_duplicate_of")),
                    _negated=True,
                ),
                name="duplicatereport_no_self_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatereport",
            constraint=models.UniqueConstraint(
                models.F("reporter"),
                models.F("suspected_duplicate_of"),
                name="duplicatereport_one_per_reporter_per_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="recommenderparticipant",
            index=models.Index(
                fields=["recommendation", "is_active"], name="recomppart_rec_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommenderparticipant",
            index=models.Index(
                fields=["account", "-created_at"], name="recomppart_account_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommenderparticipant",
            index=models.Index(
                fields=["recommendation", "reactivation_number"],
                name="recomppart_rec_react_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommenderparticipant",
            index=models.Index(
                fields=["recommendation", "locked_amount_lamports"],
                name="recomppart_rec_stake_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommenderparticipant",
            constraint=models.UniqueConstraint(
                models.F("recommendation"),
                condition=models.Q(("is_active", True)),
                name="recommenderparticipant_one_active_per_recommendation",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommenderparticipant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("locked_amount_lamports", 0),
                    ("locked_amount_lamports__gte", 200000000),
                    _connector="OR",
                ),
                name="recommenderparticipant_no_dust_balance",
            ),
        ),
        migrations.AddIndex(
            model_name="reputationevent",
            index=models.Index(
                fields=["account", "-created_at"], name="repevent_account_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reputationevent",
            index=models.Index(
                fields=["account", "event_type"], name="repevent_account_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reputationevent",
            index=models.Index(fields=["recommendation"], name="repevent_rec_idx"),
        ),
        migrations.AddIndex(
            model_name="support",
            index=models.Index(
                fields=["recommendation", "supporter_number"],
                name="support_rec_supporter_num_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="support",
            index=models.Index(
                fields=["supporter", "-created_at"],
                name="support_supporter_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="support",
            index=models.Index(
                fields=["recommendation", "recommendation_cycle_number"],
                name="support_rec_cycle_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="support",
            index=models.Index(fields=["created_at"], name="support_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="support",
            constraint=models.UniqueConstraint(
                models.F("recommendation"),
                models.F("supporter_number"),
                name="support_supporter_number_unique_per_recommendation",
            ),
        ),
        migrations.AddConstraint(
            model_name="support",
            constraint=models.UniqueConstraint(
                models.F("supporter"),
                models.F("recommendation"),
                name="support_one_per_supporter_per_recommendation",
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["duplicate_risk_status", "-created_at"],
                name="bookrec_risk_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["review_status", "-created_at"],
                name="bookrec_review_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["title_normalized", "author_names_normalized", "page_type"],
                name="bookrec_norm_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="support",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_lamports__gte", 10000000)),
                name="support_amount_min_10m_lamports",
            ),
        ),
        migrations.AddIndex(
            model_name="support",
            index=models.Index(
                fields=[
                    "recommendation",
                    "recommendation_cycle_number",
                    "supporter_number",
                ],
                name="support_rec_cycle_num_idx",
            ),
        ),
    ]
