# Generated by Django 5.2.15 on 2026-09-23 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="support",
            constraint=models.UniqueConstraint(
                models.F("on_chain_support_transaction"),
                name="support_onchain_transaction_unique",
            ),
        ),
    ]
