# Generated by Django 5.2.15 on 2026-09-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0002_support_support_onchain_transaction_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookrecommendation",
            name="cover_image_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
