# Generated by Django 5.2.15 on 2026-09-24 09:20

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0003_bookrecommendation_cover_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookrecommendation",
            name="bookrecommendation_canonical_work_unique",
        ),
        migrations.RemoveIndex(
            model_name="bookrecommendation",
            name="bookrec_cat_status_support_idx",
        ),
        migrations.RemoveIndex(
            model_name="bookrecommendation",
            name="bookrec_norm_lookup_idx",
        ),
        migrations.RenameField(
            model_name="bookrecommendation",
            old_name="author_names",
            new_name="creator_names",
        ),
        migrations.RenameField(
            model_name="bookrecommendation",
            old_name="author_names_normalized",
            new_name="creator_names_normalized",
        ),
        migrations.RemoveField(
            model_name="bookrecommendation",
            name="category",
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="recommendations",
                to="recommendations.category",
            ),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("BOOK", "Book"),
                    ("MOVIE", "Movie"),
                    ("SERIES", "Series"),
                    ("PODCAST", "Podcast"),
                    ("GAME", "Game"),
                    ("APP", "Application"),
                    ("TECH", "Tech"),
                ],
                default="BOOK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="edition_format",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="episode_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="language",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="platform",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="release_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="runtime_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookrecommendation",
            name="season_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOOK", "Book"),
                    ("MOVIE", "Movie"),
                    ("SERIES", "Series"),
                    ("PODCAST", "Podcast"),
                    ("GAME", "Game"),
                    ("APP", "Application"),
                    ("TECH", "Tech"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["content_type", "status", "-support_count"],
                name="bookrec_ct_status_support_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookrecommendation",
            index=models.Index(
                fields=["title_normalized", "creator_names_normalized", "page_type"],
                name="bookrec_norm_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookrecommendation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title_normalized"),
                django.db.models.functions.text.Lower("creator_names_normalized"),
                models.F("page_type"),
                condition=models.Q(("is_canonical", True)),
                name="bookrecommendation_canonical_work_unique",
            ),
        ),
    ]
