# Generated by Django 5.2.15 on 2026-09-24 09:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recommendations",
            "0004_remove_bookrecommendation_bookrecommendation_canonical_work_unique_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookRecommendation",
            new_name="Recommendation",
        ),
        migrations.RemoveConstraint(
            model_name="recommendation",
            name="bookrecommendation_canonical_work_unique",
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title_normalized"),
                django.db.models.functions.text.Lower("creator_names_normalized"),
                models.F("page_type"),
                condition=models.Q(("is_canonical", True)),
                name="recommendation_canonical_work_unique",
            ),
        ),
    ]
